# Usamos la imagen oficial de OpenJDK 17
FROM openjdk:17-jdk-slim

# Directorio de la app
WORKDIR /app

# Copiamos el JAR generado por Spring Boot
COPY build/libs/*.jar app.jar

# Exponemos el puerto que usamos en Spring Boot
EXPOSE 8080

# Ejecutamos la app
ENTRYPOINT ["java","-jar","app.jar"]
